### ISSUE TITLE
Interpreting the columns of the dataset

### ISSUE THREAD

**Issue by Zoher15** [copenlu/politihop#2]
Hi all :)

Really interesting dataset and I am interested in using it for research. Could you elaborate the column descriptions?  Perhaps with an example of a politifact report?

Best,
Zoher

**Comment by Zoher15** [comment]
![image](https://user-images.githubusercontent.com/29090730/104139498-ed297f00-5379-11eb-8f8d-9e1193feed04.png)
Okay this example in the appendix was helpful!

However I notice a discrepancy in the indexing. I am assuming it is an error in the appendix but does the indexing begin from 1 or 0 for sentences indexes in the annotated evidence column?

Also correct me if I am wrong, I am assuming the urls sentence list is to provide the original external article of that information. If so, were those original external articles used in training for any of the results in the paper? Or is it a setup for another task of retrieving-evidence-from-external-url? 

Thank you :)

Best,
Zoher

**Comment by lemminkainen94** [comment]
Hello Zoher!

Glad you're interested in the dataset.

Yes, it looks like the appendix is wrong. The sentences are indexed from 0 in the dataset, so annotated evidence sentences can have indices between 0 and n-1, where n is the number of sentences in the corresponding article.

Url annotations were not used in any experiments in the paper. We planned to do another experiment with the model getting the linked articles instead of Politifact articles, but we never got to it.

I'll look into the dataset description and hopefully make it a bit clearer.

Best wishes,
Wojtek

**Comment by lemminkainen94** [comment]
By the way, could you tell me which column descriptions are confusing? Talking about the descriptions from readme.

**Comment by Zoher15** [comment]
Hi Wojtek!

Thanks for your response. That explains it! I was mainly confused by the url columns, cause it was not mentioned in the paper. Otherwise, once I saw the example in the appendix, I was able to map the intention of each column. 

Having said that, maybe iterating through that appendix example in your readme might help? 

Thanks!

Best,
Zoher

**Comment by Zoher15** [comment]
Hi @lemminkainen94 ,

Some of the annotated evidence has this: (test article ID 17994)
`'{"1": ["7", "8"], "2": ["30", "31", "32,20", "33"], "3": ["37", "38", "39"], "0": ["14", "15", "18", "19", "20", "21"]}'`

If list value is joint like **32,20**, what is the interpretation?

Best,
Zoher

**Comment by rn-v** [comment]
Hi @Zoher15!

Thanks for your interest and for bringing up this important tidbit! Will add information about this in the next update.  
The list value for a particular annotated evidence denotes equivalent sentences. That is, the two sentences from the article are paraphrases of each other and play an equivalent role as evidence for the claim in question.

Hope that helps!

Best,
Arnav

**Comment by Zoher15** [comment]
Appreciate the clarification @rn-v !

I had also opened another issue about leader-board, it would be great to get some insight on that.

Thanks!

Zoher
