### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Zoher15** [copenlu/politihop#3]
Hi Wojtek,

I was wondering if there were any plans to maintain a leaderboard or an API that could be used to test different methods. [DREAM](https://arxiv.org/abs/1909.03745) and [GEAR](https://arxiv.org/abs/1908.01843) seem like two relevant methods that the baseline Transformer-XH could be compared against.

Best,
Zoher

**Comment by rn-v** [comment]
Hi Zoher,

Sorry about the delayed response.
At the moment, there are no plans of maintaining a leaderboard or API on the dataset, though I do think that would be really valuable resource and make it a convenient test bed for different methods!

Best,
Arnav

**Comment by rn-v** [comment]
Closing this now. Feel free to reopen the issue if you have any doubts/clarifications.
