### ISSUE TITLE
Question Regarding Evidence Retrieval Results

### ISSUE THREAD

**Issue by Zoher15** [copenlu/politihop#4]
Hi @rn-v,

Since for any given claim there are multiple evidence chains, and only one chain is needed for claim verification (experimental setup page 3), what does the f1 score of evidence retrieval in table 6 mean? Is it a retrieval f1 for all chains, or is it a max-f1 i.e. the score for the most well retrieved chain?

Thank you!

Best,
Zoher

**Comment by rn-v** [comment]
Hi @Zoher15!
Github isn't allowing @lemminkainen94 to comment for some reason so posting on their behalf. 

> Hello Zoher!
> 
> Yes, retrieving at least one chain of evidence is sufficient for evidence f1 score, i.e. if you correctly retrieve any one of evidence sets, you get the point.
> 
> Cheers,
> Wojtek
